### ISSUE TITLE
int array decoding result

### ISSUE THREAD

**Issue by esaulpaugh** [cleanunicorn/santoku-website#1]
ABI: 0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000

Type list: uint8[2] arr

Expected:

[1, 0]

Actual:

256

**Comment by cleanunicorn** [comment]
Let me check this.

**Comment by cleanunicorn** [comment]
@esaulpaugh Thank you for the report!

I can confirm there's a bug. Will push a fix and close this once it's done.

**Comment by cleanunicorn** [comment]
Fixed the issue, now it is displayed like this:

![image](https://user-images.githubusercontent.com/547012/86758677-b1b99b00-c04c-11ea-81c9-bbbc5878f5c5.png)

I might have other problems when displaying arrays. And I need to rethink how to render arrays altogether.
